apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
  namespace: gowrish-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms-container
        image: gowrish006/gowrish-bms:v2
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: bms-app-config
